// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhFvmx5VS0y2FhSMwU7vl-Ce2vN5dGbos',
    appId: '1:216388526790:web:1bf93ea1661ca229c86dc7',
    messagingSenderId: '216388526790',
    projectId: 'transova',
    authDomain: 'transova.firebaseapp.com',
    databaseURL: 'https://transova-default-rtdb.firebaseio.com',
    storageBucket: 'transova.firebasestorage.app',
    measurementId: 'G-R43F4X68LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHpj7Gn3CU_Jh3ItcM0dSkHMkpK5bKxu4',
    appId: '1:216388526790:android:95f6d43597c6679ec86dc7',
    messagingSenderId: '216388526790',
    projectId: 'transova',
    databaseURL: 'https://transova-default-rtdb.firebaseio.com',
    storageBucket: 'transova.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE809JJVn9Nxk7xyWclYjFpZjDviXV344',
    appId: '1:216388526790:ios:3183e78a15e87f88c86dc7',
    messagingSenderId: '216388526790',
    projectId: 'transova',
    databaseURL: 'https://transova-default-rtdb.firebaseio.com',
    storageBucket: 'transova.firebasestorage.app',
    iosBundleId: 'com.example.transova',
  );
}
